// <auto-generated />
namespace BookingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mgrv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgrv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201706110942281_mgr-v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
