//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }

        [ForeignKey("Accomodation")]
        public int Accomodation_Id { get; set; }
        public virtual Accomodation Accomodation { get; set; }

        [ForeignKey("AppUser")]
        public int AppUser_Id { get; set; }
        public virtual AppUser AppUser { get; set; }

    }
}
